// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  referenceSidebar: [
    {
      type: 'category',
      label: 'Personas',
      link: {
        type: 'doc',
        id: 'reference/Personas'
      },
      items: [
        {
          type: 'link',
          label: 'allPersonas',
          href: '/docs/reference/Personas#allPersonas'
        },
        {
          type: 'link',
          label: 'personaById',
          href: '/docs/reference/Personas/#personaById'
        },
        {
          type: 'link',
          label: 'personaByName',
          href: '/docs/reference/Personas/#personaByName'
        },
        {
          type: 'link',
          label: 'personaFusionById',
          href: '/docs/reference/Personas/#personaFusionById'
        },
        {
          type: 'link',
          label: 'personaFusionByName',
          href: '/docs/reference/Personas/#personaFusionByName'
        },
        {
          type: 'link',
          label: 'personaRecipesById',
          href: '/docs/reference/Personas/#personaRecipesById'
        }
      ]
    },
    {
      type: 'category',
      label: 'Skills',
      link: {
        type: 'doc',
        id: 'reference/Skills'
      },
      items: [
        {
          type: 'link',
          label: 'allSkills',
          href: '/docs/reference/Skills/#allSkills'
        },
        {
          type: 'link',
          label: 'skillById',
          href: '/docs/reference/Skills/#skillById'
        },
        {
          type: 'link',
          label: 'skillByName',
          href: '/docs/reference/Skills/#skillByName'
        }
      ]
    }
  ],
};

module.exports = sidebars;
